module.exports = {
  port: 3001, // Website listen port. default: 3001

  sshPort: 22, // SSH server listen port, just use it for login. default: 22

  ssl : null, // http model, Unsafe,  default: null.
  /*
  ssl: {  // Or provide an Object {cert, key} to enter https model: 
    cert: '/somedir/cert.pem',
    key: '/somedir/privkey.pem'
  },
  */
  
  sessionSecret: '{{sessionSecret}}' // Use for express-session. generated by init. You don't need modify it.

};